name: Metrics
cost: 2-3 REST requests
category: github
index: 0
supports:
  - user
inputs:

  # Enable or disable plugin
  plugin_isocalendar:
    description: Display an isometric view of your commits calendar
    type: boolean
    default: no

  # Set time window shown by isometric calendar
  plugin_isocalendar_duration:
    description: Set time window shown by isometric calendar
    type: string
    default: half-year
    values:
      - half-year
      - full-year
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
      - uses: lowlighter/metrics@latest
        with:
          # ... other options
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
